"""
validation/models.py
====================
All dataclasses used across the AIVE Validation Suite.

Dataclasses defined here:
  - TestResult           — single test outcome
  - SuiteReport          — aggregate run report (invariant: passed + failed + errored == total_tests)
  - ExtractionGroundTruth — fixture ground truth for T1
  - ExtractionScore      — LLM-as-judge output for T1
  - NoveltyResult        — external search verdict for T4
  - FounderResponse      — simulated / real founder panel answer (T5)
  - InvestorResponse     — simulated / real investor panel answer (T6)
  - EdgeAuditResult      — single edge verdict from GraphAuditor (T7)
  - GraphAuditReport     — aggregate graph audit for T7
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal


# ---------------------------------------------------------------------------
# Core result types
# ---------------------------------------------------------------------------

@dataclass
class TestResult:
    """Captures the outcome of a single validation test."""

    test_id: str
    """Short identifier, e.g. 'T1'."""

    test_name: str
    """Human-readable name, e.g. 'Extraction Accuracy Test'."""

    run_id: str
    """Foreign key linking this result to a SuiteReport run."""

    passed: bool
    """True when the test met all pass thresholds."""

    scores: dict[str, float] = field(default_factory=dict)
    """Numeric scores produced by the test, e.g. {'avg_problem_accuracy': 9.1}."""

    threshold: dict[str, float] = field(default_factory=dict)
    """Pass thresholds corresponding to each score key."""

    details: dict = field(default_factory=dict)
    """Arbitrary structured detail payload (per-item results, warnings, etc.)."""

    error: str | None = None
    """Short error code or message when the test errored; None on clean runs."""

    created_at: str = ""
    """ISO-8601 timestamp of when this result was recorded."""


@dataclass
class SuiteReport:
    """
    Aggregate report for one complete validation run.

    Invariant (enforced in __post_init__):
        passed + failed + errored == total_tests
    """

    run_id: str
    """Unique identifier for this run."""

    label: str
    """Human-readable label attached to this run."""

    total_tests: int
    """Number of tests that were scheduled to run."""

    passed: int
    """Count of tests that passed."""

    failed: int
    """Count of tests that failed (ran to completion but did not pass)."""

    errored: int
    """Count of tests that raised an unhandled exception."""

    pass_rate: float
    """passed / total_tests, in [0.0, 1.0]."""

    results: list[TestResult] = field(default_factory=list)
    """Ordered per-test results."""

    summary: str = ""
    """Markdown or plain-text summary generated by the suite runner."""

    created_at: str = ""
    """ISO-8601 timestamp of when this report was generated."""

    def __post_init__(self) -> None:
        if self.passed + self.failed + self.errored != self.total_tests:
            raise ValueError(
                f"SuiteReport invariant violated: "
                f"passed ({self.passed}) + failed ({self.failed}) + "
                f"errored ({self.errored}) = "
                f"{self.passed + self.failed + self.errored} "
                f"!= total_tests ({self.total_tests})"
            )


# ---------------------------------------------------------------------------
# T1 — Extraction Accuracy
# ---------------------------------------------------------------------------

@dataclass
class ExtractionGroundTruth:
    """
    Ground-truth fixture for a single document item used in T1.
    Stored in validation/fixtures/extraction_fixtures.json.
    """

    item_id: str
    """Unique identifier for this fixture item."""

    item_type: Literal["paper", "patent", "startup"]
    """Source document type."""

    difficulty: Literal["easy", "medium", "hard"]
    """Subjective difficulty level for the extraction task."""

    expected_problem: str
    """The correct problem statement the analyst should extract."""

    expected_technology: str
    """The correct technology the analyst should identify."""

    expected_keywords: list[str] = field(default_factory=list)
    """Canonical keywords that should appear in the extraction."""

    source_sentences: list[str] = field(default_factory=list)
    """Sentences from the source document that ground the expected fields."""


@dataclass
class ExtractionScore:
    """LLM-as-judge verdict for one extraction vs. its ground truth."""

    problem_accuracy: float
    """Accuracy of the extracted problem statement, in [0.0, 10.0]."""

    technology_accuracy: float
    """Accuracy of the extracted technology field, in [0.0, 10.0]."""

    hallucination_count: int
    """Number of claims unambiguously absent from the source document."""

    hallucinated_claims: list[str] = field(default_factory=list)
    """The specific hallucinated claims identified by the judge."""

    passed: bool = False
    """True when both accuracy scores are above threshold and hallucination_count is low."""

    def __post_init__(self) -> None:
        if not (0.0 <= self.problem_accuracy <= 10.0):
            raise ValueError(
                f"problem_accuracy must be in [0.0, 10.0], got {self.problem_accuracy}"
            )
        if not (0.0 <= self.technology_accuracy <= 10.0):
            raise ValueError(
                f"technology_accuracy must be in [0.0, 10.0], got {self.technology_accuracy}"
            )
        if self.hallucination_count < 0:
            raise ValueError(
                f"hallucination_count must be non-negative, got {self.hallucination_count}"
            )


# ---------------------------------------------------------------------------
# T4 — Novelty Search
# ---------------------------------------------------------------------------

@dataclass
class NoveltyResult:
    """External search verdict for one opportunity."""

    opportunity_id: str
    """Identifier of the opportunity being evaluated."""

    verdict: Literal["novel", "exists", "uncertain"]
    """
    novel     — no matching product found in any searched source
    exists    — at least one source returned a near-exact match
    uncertain — one or more searches timed out; classification deferred
    """

    matching_products: list[str] = field(default_factory=list)
    """Product names / URLs returned when verdict == 'exists'."""

    search_queries: list[str] = field(default_factory=list)
    """The actual queries sent to external sources."""

    confidence: float = 0.0
    """Confidence score in [0.0, 1.0] for the verdict."""


# ---------------------------------------------------------------------------
# T5 — Founder Panel
# ---------------------------------------------------------------------------

@dataclass
class FounderResponse:
    """One founder persona's answers during the T5 panel."""

    persona_id: str
    """Identifier for the simulated (or real) founder persona."""

    would_pay: bool
    """Would the founder pay for this insight?"""

    would_build: bool
    """Would the founder build this opportunity?"""

    would_not_find_themselves: bool
    """Would the founder NOT have found this opportunity on their own?"""

    reasoning: str = ""
    """Free-text reasoning from the founder persona."""


# ---------------------------------------------------------------------------
# T6 — Investor Panel
# ---------------------------------------------------------------------------

@dataclass
class InvestorResponse:
    """One investor persona's reaction during the T6 panel."""

    persona: str
    """Investor persona name, e.g. 'YC Partner', 'Sequoia Partner'."""

    reaction: Literal["Interesting", "Massive opportunity", "Pass"]
    """Categorical reaction to the opportunity."""

    reasoning: str = ""
    """Explanation of the reaction."""

    follow_up_questions: list[str] = field(default_factory=list)
    """Questions the investor would ask the founding team."""


# ---------------------------------------------------------------------------
# T7 — Graph Quality
# ---------------------------------------------------------------------------

@dataclass
class EdgeAuditResult:
    """LLM audit verdict for one knowledge-graph edge."""

    edge_id: str
    """Primary key of the edge in aive.db."""

    from_label: str
    """Label of the source node."""

    to_label: str
    """Label of the target node."""

    relationship: str
    """The relationship type / predicate on this edge."""

    is_valid: bool
    """True when the LLM judges the relationship semantically sound."""

    reasoning: str = ""
    """LLM-provided explanation for the verdict."""

    confidence: float = 0.0
    """Confidence score in [0.0, 1.0] for the is_valid judgment."""


@dataclass
class GraphAuditReport:
    """Aggregate result of auditing a sample of knowledge-graph edges."""

    edges: list[EdgeAuditResult] = field(default_factory=list)
    """Per-edge audit results."""

    precision: float = 0.0
    """valid_count / total_audited — fraction of edges judged semantically valid."""

    passed: bool = False
    """True when precision > 0.90."""

    total_audited: int = 0
    """Total number of edges that were audited (including errors)."""

    valid_count: int = 0
    """Number of edges where is_valid == True."""

    error_count: int = 0
    """Number of edges where the LLM call failed."""
